# configs/config.yaml

data_paths:
  dump: "data/dump"
  raw: "data/raw"
  ground_truth: "data/ground_truth"
  jsons: "data/jsons"
  extracted: "data/extracted"
  embeddings_PDF: "data/embeddings_PDF"
  embeddings_GT: "data/embeddings_GT"
  pdfs: "data/pdfs"

wikipedia:
  num_articles: 50
  snapshot: "20220301.en"
  seed: 42

pdf_generation:
  layouts:  # Enable/disable layouts here
    one_column: false
    two_column: false
    header_footer: true


# embedding_model: "sentence-transformers/all-MiniLM-L6-v2"

# extractors:
#   - grobid
#   - pdfminer
#   - pdftotext
#   - scienceparse
#   - unstructured

# ml:
#   similarity_metric: "cosine"
#   model_type: "random_forest"
#   cross_validation_folds: 5
