# configs/config.yaml

data_paths:
  dump: "data/dump"
  raw: "data/raw"
  ground_truth: "data/ground_truth"
  jsons: "data/jsons"
  extracted: "data/extracted"
  extracted_sentence: "data/extracted_sentence"
  embeddings_PDF: "data/embeddings_PDF"
  embeddings_GT: "data/embeddings_GT"
  pdfs: "data/pdfs"
  training_data: "data/training_data"
  extractor_summary: "data/extractor_summary"

wikipedia:
  num_articles: 50
  snapshot: "20220301.en"
  seed: 42

pdf_generation:
  layouts:  # Enable/disable layouts here
    one_column: true
    two_column: true
    header_footer: true

extraction:
  extractors:
    pypdf2: true
    ocr: true
    plumber: true

pipeline:
  extract_raw: false
  convert_json: false
  render_pdfs: false
  run_extractors: false
  generate_gt_sentences: false
  generate_extracted_sentences: false
  embed_gt: false
  embed_extracted: false
  generate_training: true

# embedding_model: "sentence-transformers/all-MiniLM-L6-v2"

# ml:
#   similarity_metric: "cosine"
#   model_type: "random_forest"
#   cross_validation_folds: 5
