# configs/config.yaml

data_paths:
  dump: "data/dump"
  raw: "data/raw"
  ground_truth: "data/ground_truth"
  extracted: "data/extracted"
  embeddings_PDF: "data/embeddings_PDF"
  embeddings_GT: "data/embeddings_GT"
  pdfs: "data/pdfs"

wikipedia:
  num_articles: 10
  snapshot: "20220301.en"

# pdf_render:
#   styles: ["prose", "multi-column", "hybrid"]
#   include_page_numbers: true

# embedding_model: "sentence-transformers/all-MiniLM-L6-v2"

# extractors:
#   - grobid
#   - pdfminer
#   - pdftotext
#   - scienceparse
#   - unstructured

# ml:
#   similarity_metric: "cosine"
#   model_type: "random_forest"
#   cross_validation_folds: 5
