# configs/config.yaml

data_paths:
  DB_dump: "data/DB_dump"
  DB_raw: "data/DB_raw"
  DB_jsons: "data/DB_jsons"
  DB_pdfs: "data/DB_pdfs"
  DB_raw_manual: "data/DB_manual_raw"
  DB_extracted: "data/DB_extracted"
  DB_ground_truth: "data/DB_ground_truth"
  DB_extracted_sentences: "data/DB_extracted_sentences"
  DB_features: "data/DB_features"
  DB_embeddings_GT: "data/DB_embeddings_GT"
  DB_embeddings_PDF: "data/DB_embeddings_PDF"
  DB_matched_sentences: "data/DB_matched_sentences"
  DB_merged_data: "data/DB_merged_data"
  DB_final_training_data: "data/DB_final_training_data"
  DB_extractor_summary: "data/DB_extractor_summary"
  DB_model_outputs: "data/DB_model_outputs"
  DB_evaluation_outputs: "data/DB_evaluation_outputs"

docbank_processing:
  line_y_tolerance: 5

extraction:
  extractors:
    pypdf2: true
    ocr: true
    plumber: true

pipeline:
  setup_docbank: false
  parse_to_json: true
  run_extractors: true
  generate_gt_sentences: true
  generate_extracted_sentences: true
  extract_features: true
  embed_gt: true
  embed_extracted: true
  match_sentences: true
  merged_data: true
  final_training_dataset: true
  run_model: true
  evaluate: true

features_to_use:
  # Structural
  - num_chars
  - num_words
  - avg_word_len
  - num_punct
  # Syntactic
  - has_verb
  - num_verbs
  - num_nouns
  - num_adjs
  - num_advs
  # Fluency
  - gpt2_perplexity
  # Inter-extractor similarity
  - jaccard_with_ocr
  - jaccard_with_plumber
  - jaccard_with_pypdf2
  - cosine_sim_with_ocr
  - cosine_sim_with_plumber
  - cosine_sim_with_pypdf2


extractor_name_map:
  pypdf2: extractor_1
  ocr: extractor_2
  plumber: extractor_3

training_config:
  resolve_ties_randomly: true
  seed: 42

model_config:
  model_selection:
    random_forest: true
    logistic_regression: false
    xgboost: false
    lightgbm: false
  data_selection:
    default: true
  data_paths:
    default: data/DB_final_training_data/training_data.csv

evaluation_paths:
  predictions_path: outputs/model_predictions.csv
  ground_truth_path: data/ground_truth.csv
  output_dir: outputs/evaluation
