# configs/config.yaml

data_paths:
  dump: "data/dump"
  raw: "data/raw"
  ground_truth: "data/ground_truth"
  jsons: "data/jsons"
  extracted: "data/extracted"
  extracted_sentences: "data/extracted_sentences"
  embeddings_PDF: "data/embeddings_PDF"
  embeddings_GT: "data/embeddings_GT"
  pdfs: "data/pdfs"
  extractor_summary: "data/extractor_summary"
  features: "data/features"
  matched_sentences: "data/matched_sentences"
  merged_data: "data/merged_data"
  final_training_data: "data/final_training_data"

wikipedia:
  num_articles: 50
  snapshot: "20220301.en"
  seed: 42

pdf_generation:
  layouts:  # Enable/disable layouts here
    one_column: true
    two_column: true
    header_footer: true

extraction:
  extractors:
    pypdf2: true
    ocr: true
    plumber: true

pipeline:
  extract_raw: false
  convert_json: false
  render_pdfs: false
  run_extractors: false
  generate_gt_sentences: false
  generate_extracted_sentences: false
  embed_gt: false
  embed_extracted: false
  extract_features: false
  match_sentences: false
  merged_data: false
  final_training_dataset: false

features_to_use:
  - similarity_score
  - num_chars
  - num_words
  - avg_word_len
  - num_punct
  - has_verb
  - num_verbs
  - num_nouns
  - num_adjs
  - num_advs
  - gpt2_perplexity

extractor_name_map:
  pypdf2: extractor_1
  ocr: extractor_2
  plumber: extractor_3

training_config:
  resolve_ties_randomly: true
  seed: 42

# ml:
#   similarity_metric: "cosine"
#   model_type: "random_forest"
#   cross_validation_folds: 5
