# configs/config.yaml

data_paths:
  DB_dump: "data/DB_dump"
  DB_raw: "data/DB_raw"
  DB_jsons: "data/DB_jsons"
  DB_pdfs: "data/DB_pdfs"
  DB_raw_manual: "data/DB_manual_raw"
  DB_extracted: "data/DB_extracted"
  DB_ground_truth: "data/DB_ground_truth"
  DB_extracted_sentences: "data/DB_extracted_sentences"
  DB_features: "data/DB_features"
  DB_embeddings_GT: "data/DB_embeddings_GT"
  DB_embeddings_PDF: "data/DB_embeddings_PDF"
  DB_matched_sentences: "data/DB_matched_sentences"
  DB_merged_data: "data/DB_merged_data"
  DB_final_training_data: "data/DB_final_training_data"
  DB_extractor_summary: "data/DB_extractor_summary"
  # jsons: "data/jsons"
  # extracted: "data/extracted"
  # extracted_sentences: "data/extracted_sentences"
  # embeddings_PDF: "data/embeddings_PDF"
  # embeddings_GT: "data/embeddings_GT"
  # extractor_summary: "data/extractor_summary"
  # features: "data/features"
  # matched_sentences: "data/matched_sentences"
  # merged_data: "data/merged_data"
  # final_training_data: "data/final_training_data"
  # model_outputs: "data/model_outputs"
  # rebuilt_documents: "data/rebuilt_documents"
  # evaluation_outputs: "data/evaluation_outputs"

docbank_processing:
  line_y_tolerance: 5

pdf_generation:
  layouts:  # Enable/disable layouts here
    one_column: true
    two_column: true
    header_footer: true
    mixed_format: true
    side_bar: true
    three_col: true
    two_col_min: true

extraction:
  extractors:
    pypdf2: true
    ocr: true
    plumber: true

pipeline:
  setup_docbank: false
  parse_to_json: false
  run_extractors: false
  generate_gt_sentences: false
  generate_extracted_sentences: false
  extract_features: false
  embed_gt: false
  embed_extracted: false
  match_sentences: false
  merged_data: false
  final_training_dataset: false
  # run_model: false
  # rebuild_documents: true
  # evaluate: true

features_to_use:
  - similarity_score
  - num_chars
  - num_words
  - avg_word_len
  - num_punct
  - has_verb
  - num_verbs
  - num_nouns
  - num_adjs
  - num_advs
  - gpt2_perplexity

extractor_name_map:
  pypdf2: extractor_1
  ocr: extractor_2
  plumber: extractor_3

training_config:
  resolve_ties_randomly: true
  seed: 42

model_config:
  model_selection:
    random_forest: true
    logistic_regression: false
    xgboost: false
    lightgbm: false
  data_selection:
    default: true
  data_paths:
    default: data/final_training_data/training_data.csv

evaluation_paths:
  predictions_path: outputs/model_predictions.csv
  ground_truth_path: data/ground_truth.csv
  output_dir: outputs/evaluation
